Add anti mt manager
KitsunePie/QAssistant pull request #34
Opened 2021-07-13 18:48 UTC by qwq233

Signed-off-by: qwq233 <qwq233@qwq2333.top>

# Title
Add anti mt manager

## 介绍 / Description
Add anti mt manager

## 更改内容 / Types of Changes
- 增强优化 Enhancement/optimization

## 检查列表 / Checklist
- [x] tested
- [x] works on my device

2021-07-13 19:14 UTC, qwq233 commented
run tests.

2021-07-14 06:19 UTC, KyuubiRan submitted a review, later dismissed

2021-07-14 06:25 UTC, qwq233 commented
run tests

2021-07-14 06:36 UTC, qwq233 commented
run tests.

2021-07-14 06:39 UTC, qwq233 commented
run tests.

2021-07-14 10:09 UTC, keta1 requested changes

2021-07-14 10:09 UTC, keta1 commented on app/src/main/cpp/Natives.cpp
> +EXPORT void Java_nil_nadph_qnotified_util_Natives_mwrite
这堆内存读写的代码，不需要

2021-07-14 10:09 UTC, keta1 commented on app/src/main/cpp/Natives.cpp
> +jboolean handleSendCardMsg(JNIEnv *env, jclass clazz, jobject rt, jobject session, jstring msg) {
这发卡片的代码更没用啊

2021-07-14 10:11 UTC, qwq233 commented on app/src/main/cpp/Natives.cpp
> +jboolean handleSendCardMsg(JNIEnv *env, jclass clazz, jobject rt, jobject session, jstring msg) {
哦 那是忘了删

2021-07-22 15:33 UTC, closed without merging