Qwq233 patch 1
KitsunePie/QAssistant pull request #36
Opened 2021-07-17 17:24 UTC by qwq233

# 移包

## 简要描述
把一些依赖扔到了libs 因为感觉根目录很乱跟qn一样
把warpper版本换成了7.1因为java 16用不了
删除了之前忘删的LICENSE文件
设置了没啥卵用的idea自动添加文件头

## 更改内容
- 增强优化 Enhancement/optimization
- 文档 Documentation
- 模板 Templates

## 检查列表

- [x] 我的代码符合本仓库的代码规范
- [ ] 我已经测试了这些更改

2021-07-17 17:40 UTC, singleNeuron requested changes

2021-07-17 17:40 UTC, singleNeuron commented on app/build.gradle
> -    buildFeatures {
你删ViewBingding干啥

2021-07-18 00:24 UTC, singleNeuron approved these changes

2021-07-18 01:05 UTC, NextAlone approved these changes

2021-07-18 02:50 UTC, KyuubiRan approved these changes

2021-07-18 04:02 UTC, merged